import type { NextPage } from "next";
import Main from "./main";
import Head from "next/head";
import { Input } from "../components/Input";
import styles from "../styles/globals.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles["container-main"]}>
      <Head>
        <title>Home | Parking controll</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>

      <Main />
    </div>
  );
};

export default Home;
