import type { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import { Input } from "../components/Input";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home | Parking controll</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Home, teste de texto capturar fonte</h1>

      <Input />
    </div>
  );
};

export default Home;
